import { create } from 'zustand';

const modos = {
  normal: {
    nombre: 'Normal',
    bg: '#2B1B3D',
    surface: '#1A3A5C',
    text: '#FFF8E7',
    textSecondary: '#FFF8E7B3',
    accent: '#FF6B3D',
    accent2: '#00D4AA',
    accent3: '#FF4582',
    accent4: '#FFE156',
    accent5: '#4DE8FF',
    success: '#00D4AA',
    error: '#E0254F',
    border: '#000000',
    borderWidth: '3px',
    sombra: '4px 4px 0px #000000',
  },
  visual: {
    nombre: 'Discapacidad visual',
    bg: '#000000',
    surface: '#111111',
    text: '#FFFFFF',
    textSecondary: '#CCCCCC',
    accent: '#FFE156',
    accent2: '#FFE156',
    accent3: '#FFFFFF',
    accent4: '#FFE156',
    accent5: '#FFFFFF',
    success: '#00FF00',
    error: '#FF4444',
    border: '#FFFFFF',
    borderWidth: '4px',
    sombra: 'none',
  },
  auditivo: {
    nombre: 'Discapacidad auditiva',
    bg: '#2B1B3D',
    surface: '#1A3A5C',
    text: '#FFF8E7',
    textSecondary: '#FFF8E7B3',
    accent: '#FF6B3D',
    accent2: '#00D4AA',
    accent3: '#FF4582',
    accent4: '#FFE156',
    accent5: '#4DE8FF',
    success: '#00D4AA',
    error: '#E0254F',
    border: '#000000',
    borderWidth: '3px',
    sombra: '4px 4px 0px #000000',
  },
  calma: {
    nombre: 'Hipersensible (calma)',
    bg: '#1A1A2E',
    surface: '#16213E',
    text: '#D0D0D0',
    textSecondary: '#999999',
    accent: '#8E8EB8',
    accent2: '#7EB8A0',
    accent3: '#B88E9E',
    accent4: '#B8B08E',
    accent5: '#8EB8B8',
    success: '#8CC98E',
    error: '#D49090',
    border: '#3A3A3A',
    borderWidth: '2px',
    sombra: 'none',
  },
  intenso: {
    nombre: 'Hiposensible (intenso)',
    bg: '#000000',
    surface: '#0A0A0A',
    text: '#FFFFFF',
    textSecondary: '#FFFFFF',
    accent: '#FF3333',
    accent2: '#00FF88',
    accent3: '#FF44AA',
    accent4: '#FFFF00',
    accent5: '#00FFFF',
    success: '#00FF00',
    error: '#FF0000',
    border: '#FFFFFF',
    borderWidth: '4px',
    sombra: '6px 6px 0px #FFFFFF',
  },
};

const useAccesibilidadStore = create((set) => ({
  modoActivo: 'normal',
  colores: modos.normal,
  tamanoTexto: 1.2,
  ondasSonido: true,
  subtitulos: true,
  reducirAnimaciones: false,
  altoContraste: false,
  escalaGrises: false,
  vibracion: false,
  intensidadEfectos: 0.5,

  setModo: (modo) => set({
    modoActivo: modo,
    colores: modos[modo],
    reducirAnimaciones: modo === 'calma',
  }),

  setTamanoTexto: (val) => set({ tamanoTexto: val }),
  setOndasSonido: (val) => set({ ondasSonido: val }),
  setSubtitulos: (val) => set({ subtitulos: val }),
  setReducirAnimaciones: (val) => set({ reducirAnimaciones: val }),
  setAltoContraste: (val) => set({ altoContraste: val }),
  setEscalaGrises: (val) => set({ escalaGrises: val }),
  setVibracion: (val) => set({ vibracion: val }),
  setIntensidadEfectos: (val) => set({ intensidadEfectos: val }),
}));

export default useAccesibilidadStore;
export { modos };
